#!/data/data/com.termux/files/usr/bin/bash
# Take a list of video files and convert everything to MP4 with
# h264 video and AAC audio (de-facto standard for Android devices)
for filename in "$@"
do
    name=$(echo $filename | rev | cut -f 2- -d '.' | rev)
    ffmpeg -i "$filename" "$name.h264.mp4" -vcodec h264 -acodec aac -crf 23 
done
